/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './horizontal-split-pane-separator.component';
const styles_HorizontalSplitSeparatorComponent:any[] = ['[_nghost-%COMP%] {\n      height: 7px;\n      background-color: #fff;\n      border-top: 1px solid #ddd;\n      cursor: ns-resize;\n    }\n    [_nghost-%COMP%]:hover {\n      background-color: #fafafa;\n    }\n    .handle[_ngcontent-%COMP%] {\n      width: 35px;\n      height: 100%;\n      background-color: #eee;\n      margin: auto;\n    }'];
export const RenderType_HorizontalSplitSeparatorComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_HorizontalSplitSeparatorComponent,
  data: {}
}
);
export function View_HorizontalSplitSeparatorComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'handle'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_HorizontalSplitSeparatorComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'horizontal-split-separator',([] as any[]),(null as any),[[
        (null as any),
        'mousedown'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      if (('mousedown' === en)) {
        const pd_0:any = ((<any>import0.ɵnov(v,1).onMousedown($event)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },View_HorizontalSplitSeparatorComponent_0,RenderType_HorizontalSplitSeparatorComponent)),
    import0.ɵdid(57344,(null as any),0,import1.HorizontalSplitSeparatorComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const HorizontalSplitSeparatorComponentNgFactory:import0.ComponentFactory<import1.HorizontalSplitSeparatorComponent> = import0.ɵccf('horizontal-split-separator',import1.HorizontalSplitSeparatorComponent,View_HorizontalSplitSeparatorComponent_Host_0,{},{notifyWillChangeSize: 'notifyWillChangeSize'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JlbmFrYV9tb29ydGhpL1Byb2plY3RzL25nMi1zcGxpdC1wYW5lL3NyYy9ob3Jpem9udGFsLXNwbGl0LXBhbmUtc2VwYXJhdG9yLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9iZW5ha2FfbW9vcnRoaS9Qcm9qZWN0cy9uZzItc3BsaXQtcGFuZS9zcmMvaG9yaXpvbnRhbC1zcGxpdC1wYW5lLXNlcGFyYXRvci5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9iZW5ha2FfbW9vcnRoaS9Qcm9qZWN0cy9uZzItc3BsaXQtcGFuZS9zcmMvaG9yaXpvbnRhbC1zcGxpdC1wYW5lLXNlcGFyYXRvci5jb21wb25lbnQudHMuSG9yaXpvbnRhbFNwbGl0U2VwYXJhdG9yQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9iZW5ha2FfbW9vcnRoaS9Qcm9qZWN0cy9uZzItc3BsaXQtcGFuZS9zcmMvaG9yaXpvbnRhbC1zcGxpdC1wYW5lLXNlcGFyYXRvci5jb21wb25lbnQudHMuSG9yaXpvbnRhbFNwbGl0U2VwYXJhdG9yQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGRpdiBjbGFzcz1cImhhbmRsZVwiPjwvZGl2PlxuICAiLCI8aG9yaXpvbnRhbC1zcGxpdC1zZXBhcmF0b3I+PC9ob3Jpem9udGFsLXNwbGl0LXNlcGFyYXRvcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDSTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQTBCOzs7Ozs7TUNEOUI7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7TUFBQTtJQUFBO2dCQUFBOzs7SUFBQTs7OyJ9
