/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './vertical-split-pane-separator.component';
const styles_VerticalSplitSeparatorComponent:any[] = ['[_nghost-%COMP%] {\n      width: 7px;\n      background-color: #fff;\n      border-left: 1px solid #ddd;\n      cursor: ew-resize;\n      position: relative;\n    }\n    [_nghost-%COMP%]:hover {\n      background-color: #fafafa;\n    }\n\n    .handle[_ngcontent-%COMP%] {\n      width: 100%;\n      height: 35px;\n      background-color: #eee;\n      position: absolute;\n      top: calc(50% - 17px);\n    }'];
export const RenderType_VerticalSplitSeparatorComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_VerticalSplitSeparatorComponent,
  data: {}
}
);
export function View_VerticalSplitSeparatorComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'handle'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_VerticalSplitSeparatorComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'vertical-split-separator',([] as any[]),(null as any),[[
        (null as any),
        'mousedown'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      if (('mousedown' === en)) {
        const pd_0:any = ((<any>import0.ɵnov(v,1).onMousedown($event)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },View_VerticalSplitSeparatorComponent_0,RenderType_VerticalSplitSeparatorComponent)),
    import0.ɵdid(57344,(null as any),0,import1.VerticalSplitSeparatorComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const VerticalSplitSeparatorComponentNgFactory:import0.ComponentFactory<import1.VerticalSplitSeparatorComponent> = import0.ɵccf('vertical-split-separator',import1.VerticalSplitSeparatorComponent,View_VerticalSplitSeparatorComponent_Host_0,{},{notifyWillChangeSize: 'notifyWillChangeSize'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JlbmFrYV9tb29ydGhpL1Byb2plY3RzL25nMi1zcGxpdC1wYW5lL3NyYy92ZXJ0aWNhbC1zcGxpdC1wYW5lLXNlcGFyYXRvci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYmVuYWthX21vb3J0aGkvUHJvamVjdHMvbmcyLXNwbGl0LXBhbmUvc3JjL3ZlcnRpY2FsLXNwbGl0LXBhbmUtc2VwYXJhdG9yLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2JlbmFrYV9tb29ydGhpL1Byb2plY3RzL25nMi1zcGxpdC1wYW5lL3NyYy92ZXJ0aWNhbC1zcGxpdC1wYW5lLXNlcGFyYXRvci5jb21wb25lbnQudHMuVmVydGljYWxTcGxpdFNlcGFyYXRvckNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvYmVuYWthX21vb3J0aGkvUHJvamVjdHMvbmcyLXNwbGl0LXBhbmUvc3JjL3ZlcnRpY2FsLXNwbGl0LXBhbmUtc2VwYXJhdG9yLmNvbXBvbmVudC50cy5WZXJ0aWNhbFNwbGl0U2VwYXJhdG9yQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGRpdiBjbGFzcz1cImhhbmRsZVwiPjwvZGl2PlxuICAiLCI8dmVydGljYWwtc3BsaXQtc2VwYXJhdG9yPjwvdmVydGljYWwtc3BsaXQtc2VwYXJhdG9yPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNJO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMEI7Ozs7OztNQ0Q5QjtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtNQUFBO0lBQUE7Z0JBQUE7OztJQUFBOzs7In0=
